"""empty message

Revision ID: ff54132b0849
Revises: 52d05398302a
Create Date: 2016-08-31 11:19:24.854708

"""

# revision identifiers, used by Alembic.
revision = 'ff54132b0849'
down_revision = '52d05398302a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('base_model')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('base_model',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created', sa.DATETIME(), nullable=True),
    sa.Column('modified', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###
